Homework 2
====================

Preprocessing
-------------

### Load Data
```{r}
setwd("~/Users/SMW/Dropbox/Coursera/DA_012213/Homework/HW2/code")
##download.file("https://spark-public.s3.amazonaws.com/dataanalysis/samsungData.rda", "../data/samsungData.rda")
load("../data/samsungData.rda")
```

### Examine raw data
```{r}
names(samsungData)
table(is.na(samsungData)) ## no NAs
table(samsungData$subject)
```
There are no NAs found.
21 subjects total, with numeric identifiers.

### Data Munging
Make variable names syntactically correct by removing parentheses, commas, etc.
```{r}
nameVec <- make.names(names(samsungData),unique=TRUE)
names(samsungData) <- nameVec
names(samsungData)
```


### make Training, Validation,and Test sets
Training and test sets include the require subjects as noted.
training set size has 13 subjects.
validation set and test set sizes are 4 subjects each.
```{r}
subjects.rest <- c(7,8,11,14,15,16,17,19,21,22,23,25,26)
set.seed(47033)
train1 <- sample(subjects.rest, 9, replace=FALSE)
train1 <- c (train1, c(1,3,5,6))
test1 <- c(27,28,29,30)
notvalid <- c(train1,test1)
#trainSet <- samsungData[samsungData$subject == c(1,3,5,6),]
trainSet <- samsungData[samsungData$subject %in% train1,]
validateSet <- samsungData[!(samsungData$subject %in% notvalid),]
testSet <- samsungData[samsungData$subject %in% test1,]
table(trainSet$subject)
table(validateSet$subject)
table(testSet$subject)
```

Pick Function
-------------
### use a tree first
```{r}
library(tree)
train.tree <- tree(factor(activity)~.,data=trainSet)
par(mfrow=c(1,1))
plot(train.tree)
text(train.tree, cex=0.5)
stree.predict <- predict(train.tree, trainSet[,-563])
head(tree.predict)
table(trainSet$activity, predict(train.tree, type="class"))
par(mfrow=c(2,1))
plot(cv.tree(train.tree,FUN=prune.tree,method="misclass"))
plot(cv.tree(train.tree))
table(validateSet$activity, predict(train.tree, validateSet[,-563], type="class"))
```
Resulting tree is OK but not great. It seems to indicate an interest it gravity!

### random Forest
```{r}
library(randomForest)
set.seed(37043)
train.rf <- randomForest(factor(activity) ~., data=trainSet, prox=TRUE)
print(train.rf)
importance(train.rf)
par(mfrow=c(1,1))
varImpPlot(train.rf, main="Importance Plot", cex=0.7)
getTree(train.rf,k=1)
table(validateSet$activity,predict(train.rf,validateSet[,-563]))
```

Cross-validate
--------------

Apply to test set
-----------------
```{r}
table(testSet$activity,predict(train.rf,testSet[,-563]))
```

### Refine if validation